# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '20e141db-f8bf-45f8-8744-e4bb89331e10'
  imageRepository: 'ecommerceadmin'
  containerRegistry: 'containerregistrygrupo1.azurecr.io'
  dockerfilePath: 'Ecommerce-code/ecommerce-admin-main/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'containerregistrygrupo10307-auth'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: linux-pool  # Nombre asignado al pool
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

    - upload: manifests
      artifact: manifests