CREATE DATABASE IF NOT EXISTS ecommerce_db;

USE ecommerce_db;

CREATE TABLE Store (
    id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255),
    userId VARCHAR(255),
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Billboard (
    id VARCHAR(255) PRIMARY KEY,
    storeId VARCHAR(255),
    label VARCHAR(255),
    imageUrl VARCHAR(255),
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (storeId) REFERENCES Store(id)
);

CREATE TABLE Category (
    id VARCHAR(255) PRIMARY KEY,
    storeId VARCHAR(255),
    billboardId VARCHAR(255),
    name VARCHAR(255),
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (storeId) REFERENCES Store(id),
    FOREIGN KEY (billboardId) REFERENCES Billboard(id)
);

CREATE TABLE Size (
    id VARCHAR(255) PRIMARY KEY,
    storeId VARCHAR(255),
    name VARCHAR(255),
    value VARCHAR(255),
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (storeId) REFERENCES Store(id)
);

CREATE TABLE Color (
    id VARCHAR(255) PRIMARY KEY,
    storeId VARCHAR(255),
    name VARCHAR(255),
    value VARCHAR(255),
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (storeId) REFERENCES Store(id)
);

CREATE TABLE Product (
    id VARCHAR(255) PRIMARY KEY,
    storeId VARCHAR(255),
    categoryId VARCHAR(255),
    name VARCHAR(255),
    price DECIMAL(10,2),
    isFeatured BOOLEAN DEFAULT FALSE,
    isArchived BOOLEAN DEFAULT FALSE,
    sizeId VARCHAR(255),
    colorId VARCHAR(255),
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (storeId) REFERENCES Store(id),
    FOREIGN KEY (categoryId) REFERENCES Category(id),
    FOREIGN KEY (sizeId) REFERENCES Size(id),
    FOREIGN KEY (colorId) REFERENCES Color(id)
);

CREATE TABLE `Order` (
    id VARCHAR(255) PRIMARY KEY,
    storeId VARCHAR(255),
    isPaid BOOLEAN DEFAULT FALSE,
    phone VARCHAR(255) DEFAULT "",
    address VARCHAR(255) DEFAULT "",
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (storeId) REFERENCES Store(id)
);

CREATE TABLE OrderItem (
    id VARCHAR(255) PRIMARY KEY,
    orderId VARCHAR(255),
    productId VARCHAR(255),
    FOREIGN KEY (orderId) REFERENCES `Order`(id),
    FOREIGN KEY (productId) REFERENCES Product(id)
);

CREATE TABLE Image (
    id VARCHAR(255) PRIMARY KEY,
    productId VARCHAR(255),
    url VARCHAR(255),
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (productId) REFERENCES Product(id) ON DELETE CASCADE
);
