name: db-Pipeline

on:
  push:
   paths:
     - db-sql/**

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Azure Container Registry
      run: |
        docker login $ {{ secrets.CONTAINER_REGISTRY }} -u {{ secrets.USERNAME }}  --password {{ secrets.PASSWORD }} 

    - name: Build and push Docker image
      run: |
        docker build ./ecommerce-admin-main -t containerRegistryGrupo1.azurecr.io/images/db-sql:0.0.${{ github.run_number }}
        docker push containerRegistryGrupo1.azurecr.io/images/db-sql:0.0.${{ github.run_number }}

    - name: Logout from Azure Container Registry
      run: docker logout containerRegistryUnique.azurecr.io
